version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: navops-db
    environment:
      POSTGRES_USER: navops_user
      POSTGRES_PASSWORD: 2102
      POSTGRES_DB: navops
    ports:
      - "5433:5432"
    volumes:
      - navops-pgdata:/var/lib/postgresql/data
      # Instanciación automática del script SQL
      - "./data base/navops.sql:/docker-entrypoint-initdb.d/navops.sql"
    restart: always

  navops-api:
    build: . # O la ruta donde esté tu Dockerfile
    container_name: navops-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      #Servicio de Claudinary
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}

      #Servicio de MSPT
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}


volumes:
  navops-pgdata:

##services:
#  # --- SERVICIO DE BASE DE DATOS ---
#  postgres:
#    image: postgres:16
#    container_name: navops-db
#    environment:
#      POSTGRES_USER: navops_user
#      POSTGRES_PASSWORD: 2102
#      POSTGRES_DB: navops
#    ports:
#      - "5433:5432"
#    volumes:
#      - navops-pgdata:/var/lib/postgresql/data
#      - "./data base/navops.sql:/docker-entrypoint-initdb.d/navops.sql"
#    restart: always
#
#  # --- SERVICIO DE TU APP (Aquí va Cloudinary) ---
#  navops-api:
#    build: . # O la ruta donde esté tu Dockerfile
#    container_name: navops-backend
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      # Configuración de DB para que Spring se conecte al contenedor de arriba
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/navops
#      - SPRING_DATASOURCE_USERNAME=navops_user
#      - SPRING_DATASOURCE_PASSWORD=2102
#
#      # VARIABLES DE CLOUDINARY (Asegúrate de que coincidan con tu application.yml)
#      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
#      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
#      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
#
#volumes:
#  navops-pgdata: