version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: navops-db
    environment:
      POSTGRES_USER: navops_user
      POSTGRES_PASSWORD: 2102
      POSTGRES_DB: navops
    ports:
      - "5433:5432"
    volumes:
      - navops-pgdata:/var/lib/postgresql/data
      # Instanciación automática del script SQL
      - "./data base/navops.sql:/docker-entrypoint-initdb.d/navops.sql"
    restart: always

  navops-api:
    build: . # O la ruta donde esté tu Dockerfile
    container_name: navops-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      #Servicio de Claudinary
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}

      #Servicio de MSPT
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}


volumes:
  navops-pgdata:

